# Generated by Django 2.2.1 on 2019-05-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created']},
        ),
    ]
