# Generated by Django 2.2.1 on 2019-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190531_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='userful',
            field=models.IntegerField(default=0),
        ),
    ]
