# Generated by Django 2.2.1 on 2019-05-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
