# Generated by Django 2.2.1 on 2019-06-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_answer_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['likes']},
        ),
    ]
